version: '3.8'

services:
  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data/
      - ./db_init:/docker-entrypoint-initdb.d
    env_file:
      - ./.env
    ports:
      - "5432:5432"

  api:
    build: .
    ports:
      - "8000:8000"
    env_file:
      - ./.env
    environment:
      - PYTHONPATH=/code
    depends_on:
      - db

volumes:
  postgres_data:
